### ISSUE TITLE
Igor Binary File reader seemingly not yet exported

### ISSUE THREAD

**Issue by mithgil** [alexriss/SpmImages.jl#3]
I saw your source code includes ibw reader. And it looks like you did not export those functions in the package. Is it still under development? Is it possible to use it?

Thanks

**Comment by alexriss** [comment]
You can just call the function `load_image("data.ibw")`, which will decide which reader to use, based on the file extension.

But yes, the ibw is not tested thoroughly - I never used these file formats myself, so I just had a few example files.

Also, as a side note, If you want ibw support in the bigger SpmImageTycoon.jl package, you need to install the dev version of the SpmImageTycoon using `install(ver="dev")`.
